"""Visualize the latest keyboard velocity log for a task.

The script reads velocity_log.csv generated by keyboard_play.py and saves PNG
plots comparing commanded velocity and actual robot velocity.
"""

import argparse
import csv
import os
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


DEFAULT_LOG_ROOT = Path("/home/user/qihang/code/unitree_lab_hanghangQAQ/dataest/visual_velocity")
DEFAULT_OUTPUT_ROOT = Path("/home/user/qihang/code/unitree_lab_hanghangQAQ/dataest/visual_velocity_plots")


def task_name_to_log_dir_name(task_name):
    known_task_names = {
        "Unitree-G1-29dof-Velocity": "velocity",
        "Unitree-G1-29dof-Velocity-Perception": "velocity_perception",
        "Unitree-G1-29dof-Velocity-Obstacle": "velocity_obstacle",
        "velocity": "velocity",
        "velocity_perception": "velocity_perception",
        "velocity_obstacle": "velocity_obstacle",
    }
    if task_name in known_task_names:
        return known_task_names[task_name]

    name = task_name
    prefix = "Unitree-G1-29dof-"
    if name.startswith(prefix):
        name = name[len(prefix):]
    name = name.lower().replace("-", "_")
    return re.sub(r"[^a-z0-9_]+", "_", name).strip("_") or "unknown_task"


def find_log_csv(log_root, task_dir_name, run_name=None):
    task_dir = log_root / task_dir_name
    if not task_dir.is_dir():
        raise FileNotFoundError(f"Task log folder not found: {task_dir}")

    if run_name is not None:
        csv_path = task_dir / run_name / "velocity_log.csv"
        if not csv_path.is_file():
            raise FileNotFoundError(f"Velocity log not found: {csv_path}")
        return csv_path

    run_dirs = [path for path in task_dir.iterdir() if path.is_dir()]
    if not run_dirs:
        raise FileNotFoundError(f"No run folders found in: {task_dir}")

    for run_dir in sorted(run_dirs, reverse=True):
        csv_path = run_dir / "velocity_log.csv"
        if csv_path.is_file():
            return csv_path

    raise FileNotFoundError(f"No velocity_log.csv found under: {task_dir}")


def read_velocity_log(csv_path):
    data = {
        "time_s": [],
        "cmd_lin_vel_x": [],
        "cmd_lin_vel_y": [],
        "cmd_ang_vel_z": [],
        "real_lin_vel_x": [],
        "real_lin_vel_y": [],
        "real_ang_vel_z": [],
    }
    with open(csv_path, newline="") as file:
        reader = csv.DictReader(file)
        for row in reader:
            for key in data:
                data[key].append(float(row[key]))

    if not data["time_s"]:
        raise ValueError(f"Velocity log is empty: {csv_path}")

    return data


def plot_axis(time_s, command, actual, title, ylabel, output_path):
    fig, ax = plt.subplots(figsize=(12, 5), dpi=160)
    ax.plot(time_s, command, label="command", linewidth=1.8)
    ax.plot(time_s, actual, label="actual", linewidth=1.4)
    ax.set_title(title)
    ax.set_xlabel("time (s)")
    ax.set_ylabel(ylabel)
    ax.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def plot_summary(data, output_path):
    series = [
        ("vx", "linear velocity x (m/s)", "cmd_lin_vel_x", "real_lin_vel_x"),
        ("vy", "linear velocity y (m/s)", "cmd_lin_vel_y", "real_lin_vel_y"),
        ("wz", "angular velocity z (rad/s)", "cmd_ang_vel_z", "real_ang_vel_z"),
    ]

    fig, axes = plt.subplots(3, 1, figsize=(13, 10), dpi=160, sharex=True)
    for ax, (name, ylabel, cmd_key, real_key) in zip(axes, series):
        ax.plot(data["time_s"], data[cmd_key], label=f"{name} command", linewidth=1.8)
        ax.plot(data["time_s"], data[real_key], label=f"{name} actual", linewidth=1.4)
        ax.set_ylabel(ylabel)
        ax.grid(True, linestyle="--", linewidth=0.5, alpha=0.5)
        ax.legend(loc="upper right")
    axes[-1].set_xlabel("time (s)")
    fig.suptitle("Keyboard Velocity Tracking")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="Visualize keyboard velocity tracking logs.")
    parser.add_argument("--task", required=True, help="Task name, for example: velocity or Unitree-G1-29dof-Velocity")
    parser.add_argument("--run", default=None, help="Run folder name. Defaults to the latest run for the task.")
    parser.add_argument("--log-root", type=Path, default=DEFAULT_LOG_ROOT, help="Root folder of velocity logs.")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT, help="Root folder for PNG outputs.")
    args = parser.parse_args()

    task_dir_name = task_name_to_log_dir_name(args.task)
    csv_path = find_log_csv(args.log_root, task_dir_name, args.run)
    data = read_velocity_log(csv_path)

    run_name = csv_path.parent.name
    output_dir = args.output_root / task_dir_name / run_name
    os.makedirs(output_dir, exist_ok=True)

    outputs = {
        "vx": output_dir / "vx.png",
        "vy": output_dir / "vy.png",
        "wz": output_dir / "wz.png",
        "summary": output_dir / "velocity_summary.png",
    }
    plot_axis(
        data["time_s"],
        data["cmd_lin_vel_x"],
        data["real_lin_vel_x"],
        "Velocity X Tracking",
        "vx (m/s)",
        outputs["vx"],
    )
    plot_axis(
        data["time_s"],
        data["cmd_lin_vel_y"],
        data["real_lin_vel_y"],
        "Velocity Y Tracking",
        "vy (m/s)",
        outputs["vy"],
    )
    plot_axis(
        data["time_s"],
        data["cmd_ang_vel_z"],
        data["real_ang_vel_z"],
        "Angular Velocity Z Tracking",
        "wz (rad/s)",
        outputs["wz"],
    )
    plot_summary(data, outputs["summary"])

    print(f"[INFO] Source CSV: {csv_path}")
    print(f"[INFO] Output folder: {output_dir}")
    for name, output_path in outputs.items():
        print(f"[INFO] {name}: {output_path}")


if __name__ == "__main__":
    main()
